// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKbjUKqeB6egYtXYmWITtBFsII4Do6h8',
    appId: '1:1880302412:web:e91404cb017eda0c',
    messagingSenderId: '1880302412',
    projectId: 'saarthi-pedagogy-a2936',
    authDomain: 'saarthi-pedagogy-a2936.firebaseapp.com',
    databaseURL: 'https://saarthi-pedagogy-a2936.firebaseio.com',
    storageBucket: 'saarthi-pedagogy-a2936.appspot.com',
    measurementId: 'G-VWB5Y0HLE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBow1iwDrWNbnumGZTW5A80DmK3FEKEU5g',
    appId: '1:1880302412:android:8ea6ed4fce4a96a0',
    messagingSenderId: '1880302412',
    projectId: 'saarthi-pedagogy-a2936',
    databaseURL: 'https://saarthi-pedagogy-a2936.firebaseio.com',
    storageBucket: 'saarthi-pedagogy-a2936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFxGn_FTztqM_jUahdlJ6qb8kFKqB16wc',
    appId: '1:1880302412:ios:4bb50cf7ce1591d1fea5e9',
    messagingSenderId: '1880302412',
    projectId: 'saarthi-pedagogy-a2936',
    databaseURL: 'https://saarthi-pedagogy-a2936.firebaseio.com',
    storageBucket: 'saarthi-pedagogy-a2936.appspot.com',
    androidClientId:
        '1880302412-qauq4681fnkblljlafdo6hlj0r0jquf9.apps.googleusercontent.com',
    iosClientId:
        '1880302412-lsv28ahbsneotjtth6snpnbmr2u7c85t.apps.googleusercontent.com',
    iosBundleId: 'com.saarthipedagogy.students',
  );
}
